### ISSUE TITLE
It would be nice to disable automatically connect when the Socket Object is initialized

### ISSUE THREAD

**Issue by hoanglu14** [fjcaetano/RxWebSocket#3]
Hi,

I think it is a good idea ti allow developer to choose when to trigger the socket connection. Sometimes I just need to initialize the socket object first, write all the beautiful reactive codes then start the connection. Like this

```
override func react() {
        let socket = RxWebSocket(url: "ws://lcocalhost:1337")
    
        let connect = socket.rx.connect
            .do(onNext: { _ in
                self.socket.write(string: self.varUsername.value ?? "Unknown user")
                self.varIsConnected.value = true
            })
            .map { true }

        let disconnect = socket.rx.disconnect
            .do(onNext: { error in
                self.varIsConnected.value = false
            })
            .map { _ in false}

        Observable.of(connect,disconnect).merge() ~> varIsConnected => disposeBag
    }
```

Then somewhere in the app, I would call 
```
 lazy var connectAction: Action<Void?, Void> = {
        return Action() { _ in
            if self.socket.isConnected {
                self.socket.disconnect()
            } else {
                self.socket.connect()
            }
            return .just(())
        }
    }()
```

But this cannot be achieved since the connection started by the time this happens
`        let socket = RxWebSocket(url: "ws://lcocalhost:1337")
`

**Comment by fjcaetano** [comment]
@hoanglu14 this may be interesting indeed, but I'm a bit hesitant of changing the current behavior, perhaps we could have a `shouldAutoconnect: Bool` argument on the initializer and set it to `true` by default. This way, you could send `false` and connect manually. What do you think about that?

Also, how do you feel about writing a PR for this?

**Comment by fjcaetano** [comment]
[Inactive thread]
