### ISSUE TITLE
Support RxSwift 5.0

### ISSUE THREAD

**Issue by mariohahn** [fjcaetano/RxWebSocket#6]
We would like to update to RxSwift 5, but at the moment your library only works with 4.x.

**Comment by fjcaetano** [comment]
Hey @mariohahn, feel free to open a PR with the upgrade, it'll be more than welcome. I don't have much time to dedicate to this library currently and all help is appreciated.

**Comment by Ravi61** [comment]
Hey @fjcaetano @mariohahn have created a pull request 
https://github.com/fjcaetano/RxWebSocket/pull/7
See if this works out.

**Comment by fjcaetano** [comment]
Fixed with #7
